# Generated by Django 5.1.5 on 2025-02-21 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_datauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 12, 20, 45, 735000)),
        ),
    ]
