# Generated by Django 5.1.6 on 2025-04-25 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_alter_datauser_created_alter_post_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 12, 26, 39, 106496)),
        ),
    ]
