# Generated by Django 5.1.6 on 2025-05-13 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_alter_blogimage_image_alter_datauser_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 2, 57, 203580)),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
