# Generated by Django 5.1.6 on 2025-05-13 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_rename_featuredblog_featuredblog0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 17, 5, 538786)),
        ),
        migrations.DeleteModel(
            name='FeaturedBlog2',
        ),
    ]
