# Generated by Django 5.1.6 on 2025-05-16 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0038_alter_datauser_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser',
            name='user',
        ),
        migrations.AddField(
            model_name='datauser',
            name='confirm_password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='datauser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='datauser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='datauser',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='datauser',
            name='username',
            field=models.CharField(default='default_username', max_length=150),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 17, 53, 53, 147825)),
        ),
    ]
