# Generated by Django 5.1.6 on 2025-05-16 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0039_remove_datauser_user_datauser_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 18, 19, 19, 376162)),
        ),
    ]
