# Generated by Django 5.1.6 on 2025-05-16 12:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0040_alter_datauser_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='username',
        ),
        migrations.AddField(
            model_name='datauser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 18, 29, 39, 186949)),
        ),
    ]
