# Generated by Django 5.1.6 on 2025-05-19 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0041_remove_datauser_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 13, 19, 20, 21515)),
        ),
    ]
