# Generated by Django 5.1.6 on 2025-05-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0042_question_views_count_alter_datauser_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='user',
        ),
        migrations.AddField(
            model_name='datauser',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='datauser',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='datauser',
            name='pass1',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AddField(
            model_name='datauser',
            name='username',
            field=models.CharField(default='username', max_length=150, unique=True),
        ),
    ]
