# Generated by Django 5.1.6 on 2025-05-19 10:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0043_remove_datauser_age_remove_datauser_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='datauser',
            name='username',
        ),
        migrations.AddField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 16, 4, 27, 692289)),
        ),
        migrations.AddField(
            model_name='datauser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='datauser',
            name='qualification',
            field=models.CharField(default='12', max_length=50),
        ),
        migrations.AddField(
            model_name='datauser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
