# Generated by Django 5.1.6 on 2025-05-21 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0044_remove_datauser_email_remove_datauser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='No short description', max_length=255),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 2, 40, 341386)),
        ),
    ]
