# Generated by Django 5.1.6 on 2025-05-21 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0045_post_short_description_alter_datauser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(default='django,blog,post', help_text='Enter at least 3 comma-separated keywords.'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 15, 15, 54, 192759)),
        ),
    ]
