# Generated by Django 5.1.6 on 2025-05-21 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0046_post_keywords_alter_datauser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.TextField(default='django,question,answer', help_text='Enter at least 3 comma-separated keywords.'),
        ),
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(default='No short description', max_length=255),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 15, 55, 56, 869727)),
        ),
    ]
