# Generated by Django 5.1.6 on 2025-05-21 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0048_alter_datauser_created_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 17, 39, 27, 908728)),
        ),
    ]
