# Generated by Django 5.1.6 on 2025-05-23 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0050_alter_datauser_created_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 21, 31, 36, 821093)),
        ),
    ]
