# Generated by Django 5.1.6 on 2025-05-23 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0051_remove_question_body_alter_datauser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 21, 36, 0, 187921)),
        ),
        migrations.AlterField(
            model_name='question',
            name='short_description',
            field=models.CharField(default='No short description', max_length=160),
        ),
    ]
