# Generated by Django 5.1.6 on 2025-05-24 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0052_alter_datauser_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 17, 39, 54, 411417)),
        ),
    ]
