# Generated by Django 5.1.6 on 2025-05-24 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0053_alter_datauser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_image',
            field=models.BooleanField(default=False, help_text='Tick this to delete the current image'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 17, 47, 11, 22369)),
        ),
    ]
