# Generated by Django 5.1.6 on 2025-05-25 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0054_post_delete_image_alter_datauser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 12, 49, 0, 649345)),
        ),
    ]
