# Generated by Django 5.1.6 on 2025-06-13 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0056_alter_datauser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 15, 0, 5, 866573)),
        ),
    ]
