# Generated by Django 5.1.6 on 2025-06-13 09:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0057_alter_datauser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 15, 4, 7, 888004)),
        ),
        migrations.CreateModel(
            name='FeaturedBlog3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedBlog4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedBlog5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post')),
            ],
        ),
    ]
